G-Epitech/DFMTY-AREA

- backend/.editorconfig
- backend/Zeus.sln
- Initialized solution
- Added two solution folders
- Added editor config
> AREA-4 - feat(backend): init zeus solution

- backend/Zeus.Api.Application/Common/Interfaces/Repositories/IUserReadRepository.cs
- backend/Zeus.Api.Application/Common/Interfaces/Repositories/IUserWriteRepository.cs
- backend/Zeus.Api.Domain/Common/Models/Entity.cs
- backend/Zeus.Api.Domain/Common/Models/ValueObject.cs
- backend/Zeus.Api.Domain/UserAggregate/ValueObjects/UserId.cs
- backend/Zeus.Api.Infrastructure/Persistence/Repositories/InMemoryUserSet.cs
- backend/Zeus.Api.Infrastructure/Persistence/Repositories/UserReadRepository.cs
- backend/Zeus.Api.Infrastructure/Persistence/Repositories/UserWriteRepository.cs
I added users repositories. I split read and write in 2 dinstinct repositories in order to improve the readability and the follow as much as possible the CQRS pattern. Also, it will allow us to have a better readability rate when we'll set up the ORM.
> AREA-23 - Add user repositories

- Jenkinsfile
- backend/Zeus.Api.Web/Dockerfile
- docker-compose.yaml
I added a docker-compose to simplify the life of our team.
Secondly, I added a step on jenkins file to test the build of our service. Here I test the build of the Web application.
> AREA-51 - WebApi docker and jenkins build

- mobile/lib/api/call.dart
- mobile/lib/api/response.dart
- mobile/lib/api/utils/dto.abstract.dart
- mobile/lib/api/utils/exceptions.dart
- mobile/lib/repositories/authentication.repository.dart
- mobile/lib/repositories/dtos/authentication.dtos.dart
- mobile/lib/repositories/dtos/authentication.dtos.g.dart
- mobile/lib/utils/json.dart
- mobile/pubspec.lock
- mobile/pubspec.yaml
- mobile/test/api/call.test.dart
- mobile/test/api/mock/auth.mock.dart
- mobile/test/main_test.dart
- mobile/test/repository/authentication.test.dart
- mobile/test/repository/repository.test.dart
I added the authentication repository. This repository is only mapping api endPoint with DTOs.
Also, I updated the API `call` function because a function like this one can't really produce a dynamically type so I removed it. And it's the repository who's just mapping request result to a DTO.
> AREA-48 - Authentication repository

- mobile/lib/mediator/authentication.mediator.dart
This mediator allow us to login/register and save our credentials with appropriate repositories.
> AREA-50 - Authentication mediator

- mobile/lib/models/user.model.dart
- mobile/lib/repositories/dtos/user.dtos.dart
- mobile/lib/repositories/dtos/user.dtos.g.dart
- mobile/lib/repositories/user.repository.dart
I created the user repository, which is used to fetch user data from the API.
For now, only the GetUser() method is implemented since I don't have any more ideas, and I didn't find any other usage.
> AREA-40 - Create user repository

- mobile/lib/app/app.dart
- mobile/lib/repositories/user.repository.dart
The User repository now needs the credentials one
> AREA-69 - Add the token in the user repository api calls

- mobile/ios/Runner/Info.plist
- mobile/lib/app/app.dart
- mobile/lib/models/integration.model.dart
- mobile/lib/repositories/dtos/integration.dtos.dart
- mobile/lib/repositories/dtos/integration.dtos.g.dart
- mobile/lib/repositories/integration.repository.dart
- mobile/lib/repositories/models/integration.repository.model.dart
- mobile/lib/repositories/models/integrations/discord.integrations.dart
- mobile/lib/repositories/models/integrations/integrations.dart
- mobile/lib/repositories/models/page.repository.model.dart
- mobile/lib/repositories/models/repository.models.dart
- mobile/lib/repositories/utils/page_serializer.utils.dart
- mobile/pubspec.lock
- mobile/pubspec.yaml
- mobile/test/repository/integration.test.dart
- mobile/test/repository/repository.test.dart
I created the integration repository.
It makes us able to fetch all integrations, or integrations by pages, or by pages and size.
>[!Note]
> Since I'm new with this technos and logics, please take a look at the logic of my work 👍
> AREA-41 - Create integration repository

- mobile/lib/api/call.dart
- mobile/lib/repositories/integration.repository.dart
- mobile/test/api/mock/auth.mock.dart
- mobile/test/main_test.dart
- mobile/test/repository/authentication.test.dart
- mobile/test/repository/integration.test.dart
As the user repository tests, I made the feature and the tests for it, but they aren't passing, and I can't find why.
> AREA-70 - Add a getIntegrationById repository method

- mobile/lib/repositories/dtos/user.dtos.dart
- mobile/lib/repositories/dtos/user.dtos.g.dart
- mobile/lib/repositories/user.repository.dart
- mobile/test/repository/repository.test.dart
- mobile/test/repository/user.test.dart
I made the tests, but they aren't passing yet, but I legit don't know how to fix it.
> AREA-67 - Make tests for the user repository

- mobile/lib/app/app.dart
- mobile/lib/app/features/home/view/home_page.view.dart
- mobile/lib/app/features/integrations/integration.dart
- mobile/lib/app/features/integrations/integration.names.dart
- mobile/lib/app/features/integrations/view/integration_page.view.dart
- mobile/lib/app/features/integrations/widgets/integration.widget.dart
- mobile/lib/app/features/integrations/widgets/integrations/discord.integrations.widget.dart
- mobile/lib/app/routes/generate.routes.dart
- mobile/lib/app/routes/routes_names.dart
- mobile/lib/app/widgets/banner.triggo.dart
- mobile/lib/app/widgets/button.triggo.dart
- mobile/lib/mediator/integration.mediator.dart
- mobile/lib/models/integration.model.dart
- mobile/lib/models/integrations/discord.integration.model.dart
- mobile/lib/repositories/dtos/integration.dtos.dart
- mobile/lib/repositories/models/integration.repository.model.dart
- mobile/lib/repositories/models/integrations/discord.integrations.dart
I created the integration page.
In this page, you'll be able to see the discord integrations (for now).
Here's a little example of how it looks:
> [!Note]
> For now, there isn't discord badges since it's not compulsory and urgent for the MVP
> AREA-55 - Create view for integration list

- backend/Zeus.Common.Extensions/Queryable/QueryableExtensions.cs
I fixed pagination total number of pages. Compute was broken due to not always needed operation.
> AREA-73 - Fix pagination total number of pages

- mobile/lib/repositories/dtos/integration.dtos.dart
- mobile/lib/repositories/dtos/integration.dtos.g.dart
- mobile/lib/repositories/integration.repository.dart
- mobile/test/repository/integration.test.dart
- mobile/test/repository/user.test.dart
I fixed the failing tests that were abandoned.
A test for the user, and some other ones for the integrations were failing, so I fixed it
> AREA-86 - Fix failing tests

- mobile/test/app/app.test.dart
- mobile/test/app/widgets/banner.triggo.test.dart
- mobile/test/app/widgets/button.triggo.test.dart
- mobile/test/app/widgets/input.triggo.test.dart
- mobile/test/app/widgets/navigation_bar.triggo.test.dart
- mobile/test/app/widgets/scaffold.triggo.test.dart
- mobile/test/app/widgets/widgets.test.dart
- mobile/test/main_test.dart
I added tests for the Triggo widgets.
Since those widgets are the most used in the project, I tested it.
> [!Note]
> Those tests aren't exhaustive and can't be improved !
> AREA-88 - Add tests for the triggo widgets

- web/src/app/features/authentication/login/components/login-form/login-form.component.ts
- web/src/app/features/automations/workspace/automations-workspace.page.ts
- web/src/styles/_toastr.scss
- web/src/styles/_typography.scss
- web/src/styles/main.scss
> AREA-99 - Improve the look of the toaster component

- backend/Zeus.Api.Presentation.Web/Controllers/Automations/AutomationController.cs
I added a simple endpoint (allow anonymous) to get automations schema
> AREA-114 - Get automations/integrations schema

- mobile/android/app/src/main/AndroidManifest.xml
- mobile/lib/app/features/integration/bloc/integrations_bloc.dart
- mobile/lib/app/features/integration/bloc/integrations_event.dart
- mobile/lib/app/features/integration/bloc/integrations_state.dart
- mobile/lib/app/features/integration/view/integrations.view.dart
- mobile/lib/app/widgets/scaffold.triggo.dart
- mobile/pubspec.lock
I added the auto reload of the integration list when another one is added.
Also fixed a bug where some phones can't be redirected to links
> AREA-95 - Add auto integration list reload

- backend/Zeus.Api.Application/Integrations/Query/Discord/GetDiscordGuildChannels/GetDiscordGuildChannelQueryResult.cs
- backend/Zeus.Api.Application/Integrations/Query/Discord/GetDiscordGuildChannels/GetDiscordGuildChannelsQuery.cs
- backend/Zeus.Api.Application/Integrations/Query/Discord/GetDiscordGuildChannels/GetDiscordGuildChannelsQueryHandler.cs
- backend/Zeus.Api.Application/Integrations/Query/Discord/GetDiscordGuildChannels/GetDiscordGuildChannelsQueryValidator.cs
- backend/Zeus.Api.Application/Interfaces/Services/Integrations/Discord/IDiscordService.cs
- backend/Zeus.Api.Application/Zeus.Api.Application.csproj
- backend/Zeus.Api.Domain/Integrations/Discord/DiscordChannel.cs
- backend/Zeus.Api.Domain/Integrations/Discord/ValueObjects/DiscordChannelId.cs
- backend/Zeus.Api.Domain/Integrations/Discord/ValueObjects/DiscordChannelType.cs
- backend/Zeus.Api.Infrastructure/Services/Integrations/Discord/Contracts/GetDiscordGuildChannelResponse.cs
- backend/Zeus.Api.Infrastructure/Services/Integrations/Discord/DiscordService.cs
- backend/Zeus.Api.Presentation.Web/Contracts/Integrations/Discord/GetDiscordGuildChannelResponse.cs
- backend/Zeus.Api.Presentation.Web/Controllers/Integrations/Discord/DiscordPropsController.cs
> AREA-118 - Add discord guilds endpoints

- mobile/lib/repositories/automation/dtos/automation.dtos.dart
- mobile/lib/repositories/automation/dtos/automation.dtos.g.dart
- mobile/lib/repositories/integration/dtos/integration.dtos.dart
- mobile/lib/repositories/integration/dtos/integration.dtos.g.dart
- mobile/lib/repositories/integration/integration.repository.dart
- mobile/lib/repositories/page/utils/page_serializer.utils.dart
To develop all our repository the same way, I deleted the `'page'` specification in the dtos
> AREA-97 - Serialize the page as a json object

- mobile/assets/icons/user.svg
- mobile/lib/app/app.dart
- mobile/lib/app/features/integration/view/integration_connect.view.dart
- mobile/lib/app/features/login/widgets/login_form.dart
- mobile/lib/app/features/profile/view/profile.view.dart
- mobile/lib/app/routes/generate.routes.dart
- mobile/lib/app/routes/routes_names.dart
- mobile/lib/app/widgets/navigation_bar.triggo.dart
- mobile/lib/mediator/user.mediator.dart
- mobile/pubspec.yaml
- mobile/test/app/widgets/navigation_bar.triggo.test.dart
- mobile/test/app/widgets/scaffold.triggo.test.dart
The design has been checked with the design master 🤓 
Here's a little example of the user profile view:
> AREA-122 - Make user profil0e view

- mobile/lib/repositories/authentication/authentication.repository.dart
- mobile/test/api/mock/auth.mock.dart
Only change refresh token route method and it work.
> AREA-103 - Fix refresh token call

- mobile/lib/app/app.dart
- mobile/lib/app/features/automation/view/automations.view.dart
- mobile/lib/app/features/automation/view/creation/parameters.view.dart
- mobile/lib/app/features/integration/view/integration_connect.view.dart
- mobile/lib/app/features/integration/view/integrations/discord.view.dart
- mobile/lib/app/features/integration/widgets/integration.widget.dart
- mobile/lib/app/features/profile/view/profile.view.dart
- mobile/lib/app/features/welcome/view/welcome.view.dart
- mobile/lib/mediator/authentication.mediator.dart
- mobile/lib/mediator/automation.mediator.dart
- mobile/lib/mediator/integration.mediator.dart
- mobile/lib/mediator/integrations/discord.mediator.dart
- mobile/lib/mediator/integrations/notion.mediator.dart
- mobile/lib/mediator/integrations/openAi.mediator.dart
- mobile/lib/mediator/user.mediator.dart
- mobile/lib/utils/launch_url.dart
- mobile/pubspec.lock
I also reset the selected icon to the home page after login in with Google (It was not done before, so the selected icon was the profile page (where we log out))
> AREA-148 - Replace the snack bar text by a real one

- mobile/lib/app/features/integration/integration.names.dart
- mobile/lib/app/features/integration/widgets/integrations/open_ai_form.widget.dart
- mobile/lib/mediator/integration.mediator.dart
- mobile/lib/models/integrations/openAI.integration.model.dart
To connect to the OpenAI integration, you need an API Token and an Admin API Token, I added links to create it
Feel free to make suggestions on the UI:
> AREA-160 - Add links to create openAI tokens

- mobile/lib/mediator/authentication.mediator.dart
I wasn't checking the register status code answer
> AREA-176 - Fix Error when registering using Google OAuth2

- Jenkinsfile
- backend/Zeus.Api.Application/Automations/Commands/CreateAutomation/CreateAutomationCommand.cs
- backend/Zeus.Api.Application/Automations/Commands/CreateAutomation/CreateAutomationCommandHandler.cs
- backend/Zeus.Api.Application/Interfaces/Repositories/IIntegrationReadRepository.cs
- backend/Zeus.Api.Domain/Errors/Automations/Errors.Automations.cs
- backend/Zeus.Api.Infrastructure/Persistence/Repositories/IntegrationReadRepository.cs
- backend/Zeus.Common.Domain/AutomationAggregate/ValueObjects/AutomationTriggerParameter.cs
- backend/Zeus.Common.Domain/ProvidersSettings/ActionSchema.cs
- backend/Zeus.Common.Domain/ProvidersSettings/IHasDependenciesSchema.cs
- backend/Zeus.Common.Domain/ProvidersSettings/ParameterSchema.cs
- backend/Zeus.Common.Domain/ProvidersSettings/ProvidersSettings.cs
- backend/Zeus.Common.Domain/ProvidersSettings/TriggerSchema.cs
- backend/Zeus.Daemon.Application/Execution/AutomationExecutionContext.cs
From now, when an automation is created, its consistency is checked otherwise errors are correctly reported.
> AREA-154 - Add automation candidate creation validation

- backend/Zeus.Api.Application/Automations/Commands/CreateAutomation/CreateAutomationCommandHandler.cs
- backend/Zeus.Api.Presentation.Web/Contracts/Automations/GetAutomationResponse.cs
- backend/Zeus.Api.Presentation.Web/Mapping/AutomationMappingConfig.cs
> fix(backend): some mapping errors

- mobile/lib/app/features/automation/bloc/automation_bloc.dart
- mobile/lib/app/features/automation/view/singleton/parameters.view.dart
- mobile/lib/app/features/integration/view/integration_connect.view.dart
Fix preselected value with facts.
> AREA-178 - Bug pre selected parameter value

- backend/Zeus.Api.Presentation.Web/Controllers/Manifest/ManifestController.cs
- backend/Zeus.Api.Presentation.Web/Manifest/ApiManifest.cs
- backend/Zeus.Api.Presentation.Web/Manifest/ApiManifestClient.cs
- backend/Zeus.Api.Presentation.Web/Manifest/ApiManifestProvider.cs
- backend/Zeus.Api.Presentation.Web/Manifest/ApiManifestServer.cs
- backend/Zeus.Api.Presentation.Web/Manifest/ApiManifestService.cs
- backend/Zeus.Api.Presentation.Web/Manifest/ApiManifestServiceElement.cs
- backend/Zeus.Api.Presentation.Web/Program.cs
- backend/Zeus.Api.Presentation.Web/appsettings.Development.json
- backend/Zeus.Api.Presentation.Web/appsettings.json
I added the route `/about.json` on the Web API.
> feat(backend): add API manifest

- backend/Zeus.Common.Domain/Resources/providers-settings.json
- mobile/lib/app/features/automation/bloc/automation_bloc.dart
- mobile/lib/app/features/automation/bloc/automation_state.dart
- mobile/lib/app/features/automation/view/singleton/main.view.dart
- mobile/lib/app/features/automation/view/singleton/parameters.view.dart
- mobile/lib/app/features/automation/view/singleton/select_integration_account.view.dart
- mobile/lib/app/features/integration/widgets/integration.widget.dart
- mobile/lib/app/features/integration/widgets/integrations/league_of_legends_form.widget.dart
- mobile/lib/mediator/automation.mediator.dart
- mobile/lib/mediator/integration.mediator.dart
- mobile/lib/models/integration.model.dart
When we are trying to update an existing automation, everything is now correctly saved. But unfortunately, backend doesn't gave us access to update an automation. :/
> AREA-177 - Bug when update existing automation

- mobile/lib/app/features/integration/view/integrations/leagueOfLegends.view.dart
- mobile/lib/app/features/integration/view/integrations/openAI.view.dart
Since it was very quick to do, I also refactored the openAI form.
Here's a little example of how it looks like:
> AREA-188 - Improve the league of legends token form

- mobile/lib/app/features/integration/view/integrations.view.dart
I'm now using `RouteWare` instead of Bloc provider
> AREA-190 - Refactor the Integration auto reload using the new way

- mobile/lib/app/features/automation/bloc/automation/automation_bloc.dart
- mobile/lib/app/features/automation/models/input.model.dart
- mobile/lib/app/features/automation/view/singleton/input.view.dart
- mobile/lib/app/features/automation/view/singleton/parameters.view.dart
- mobile/lib/app/features/automation/view/singleton/select_integration_account.view.dart
- mobile/lib/app/features/integration/widgets/integration.widget.dart
I added ability to give a simple emoji ❤️
> AREA-165 | AREA-164 - Add automation emoji input

- mobile/lib/app/features/automation/bloc/automation/automation_bloc.dart
- mobile/lib/app/features/automation/view/singleton/main.view.dart
- mobile/lib/app/features/automation/view/singleton/parameters.view.dart
- mobile/lib/app/features/automation/view/singleton/settings.view.dart
We are now able to remove an action.
Also, I added some warning that prevent us that a fill became `null`
> AREA-166 - Remove automation action

- mobile/lib/app/features/automation/bloc/automation/automation_bloc.dart
- mobile/lib/app/features/automation/bloc/automation/automation_event.dart
- mobile/lib/app/features/automation/bloc/automation/automation_state.dart
- mobile/lib/app/features/automation/view/singleton/main.view.dart
- mobile/lib/app/features/automation/view/singleton/settings.view.dart
- mobile/lib/app/routes/custom.router.dart
- mobile/lib/app/routes/generate.routes.dart
- mobile/lib/mediator/automation.mediator.dart
- mobile/lib/repositories/automation/automation.repository.dart
- mobile/lib/repositories/automation/dtos/automation.dtos.dart
- mobile/lib/repositories/automation/dtos/automation.dtos.g.dart
Added a button to remove the created automations but isn't working for now since the backend endpoint isn't done yet.
Here's an example of how it looks:
> AREA-189 - Remove an automation
